// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALrNgKCg734MjfzrPNlQP5G9Iu_j_mNU8',
    appId: '1:543344590547:web:0552313c3007d66bf45e26',
    messagingSenderId: '543344590547',
    projectId: 'dev-talks-99bab',
    authDomain: 'dev-talks-99bab.firebaseapp.com',
    storageBucket: 'dev-talks-99bab.appspot.com',
    measurementId: 'G-KDBHXQWVF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsM1QBrzfHwsjNOsoUiXrpLcTaCwvmt2E',
    appId: '1:543344590547:android:9743d4e0a2b76bc5f45e26',
    messagingSenderId: '543344590547',
    projectId: 'dev-talks-99bab',
    storageBucket: 'dev-talks-99bab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzo-FxOUqLyZEbTDlA2p6mV-o8Zvgw2sM',
    appId: '1:543344590547:ios:95cfd492d6378e26f45e26',
    messagingSenderId: '543344590547',
    projectId: 'dev-talks-99bab',
    storageBucket: 'dev-talks-99bab.appspot.com',
    iosBundleId: 'com.example.devTalks',
  );
}
